import graphics as gr

window = gr.GraphWin("Minecraft", 800, 600)
window.setBackground('aqua')
my_rectangle = gr.Rectangle(gr.Point(0, 350), gr.Point(800, 800))
my_rectangle.draw(window)
my_rectangle.setFill('green')
my_circle = gr.Circle(gr.Point(100, 100), 25)
my_circle.draw(window)
my_circle.setFill('white')
my_circle = gr.Circle(gr.Point(120, 100), 25)
my_circle.draw(window)
my_circle.setFill('white')
my_circle = gr.Circle(gr.Point(90, 120), 25)
my_circle.draw(window)
my_circle.setFill('white')
my_circle = gr.Circle(gr.Point(110, 120), 25)
my_circle.draw(window)
my_circle.setFill('white')
my_circle = gr.Circle(gr.Point(130, 120), 25)
my_circle.draw(window)
my_circle.setFill('white')
my_circle = gr.Circle(gr.Point(600, 120), 50)
my_circle.draw(window)
my_circle.setFill('yellow')
my_triangle = gr.Polygon(gr.Point(40, 350), gr.Point(70, 250),gr.Point(100, 350))
my_triangle.draw(window)
my_triangle.setFill('grey')
my_triangle = gr.Polygon(gr.Point(60, 350), gr.Point(120, 200),gr.Point(175, 350))
my_triangle.draw(window)
my_triangle.setFill('grey')
my_triangle = gr.Polygon(gr.Point(130, 350), gr.Point(160, 250),gr.Point(180, 350))
my_triangle.draw(window)
my_triangle.setFill('grey')
my_rectangle = gr.Rectangle(gr.Point(300, 225), gr.Point(500, 450))
my_rectangle.setWidth(5)
my_rectangle.draw(window)
my_rectangle.setFill('red')
my_triangle = gr.Polygon(gr.Point(300, 225), gr.Point(400, 150),gr.Point(500, 225))
my_triangle.draw(window)
my_triangle.setWidth(5)
my_triangle.setFill('pink')
my_rectangle = gr.Rectangle(gr.Point(350, 275), gr.Point(450, 375))
my_rectangle.setWidth(3)
my_rectangle.draw(window)
my_rectangle.setFill('yellow')
my_line = gr.Line(gr.Point(350, 325), gr.Point(450, 325))
my_line.setWidth(3)
my_line.draw(window)
my_line = gr.Line(gr.Point(400, 275), gr.Point(400, 375))
my_line.setWidth(3)
my_line.draw(window)
my_rectangle = gr.Rectangle(gr.Point(640, 300), gr.Point(650, 475))
my_rectangle.setWidth(1)
my_rectangle.draw(window)
my_rectangle.setFill('orange')
my_circle = gr.Circle(gr.Point(645, 270), 30)
my_circle.draw(window)
my_circle.setFill('darkgreen')
my_circle = gr.Circle(gr.Point(620, 300), 30)
my_circle.draw(window)
my_circle.setFill('darkgreen')
my_circle = gr.Circle(gr.Point(670, 300), 30)
my_circle.draw(window)
my_circle.setFill('darkgreen')

my_circle = gr.Circle(gr.Point(300, 100), 25)
my_circle.draw(window)
my_circle.setFill('white')
my_circle = gr.Circle(gr.Point(320, 100), 25)
my_circle.draw(window)
my_circle.setFill('white')
my_circle = gr.Circle(gr.Point(290, 120), 25)
my_circle.draw(window)
my_circle.setFill('white')
my_circle = gr.Circle(gr.Point(310, 120), 25)
my_circle.draw(window)
my_circle.setFill('white')
my_circle = gr.Circle(gr.Point(330, 120), 25)
my_circle.draw(window)
my_circle.setFill('white')

my_circle = gr.Circle(gr.Point(200, 100), 25)
my_circle.draw(window)
my_circle.setFill('white')
my_circle = gr.Circle(gr.Point(220, 100), 25)
my_circle.draw(window)
my_circle.setFill('white')
my_circle = gr.Circle(gr.Point(190, 120), 25)
my_circle.draw(window)
my_circle.setFill('white')
my_circle = gr.Circle(gr.Point(210, 120), 25)
my_circle.draw(window)
my_circle.setFill('white')
my_circle = gr.Circle(gr.Point(230, 120), 25)
my_circle.draw(window)
my_circle.setFill('white')


window.getMouse()
window.close()
